class TaskError(Exception):
    """Исключение, связанное с ошибками в задачах."""
    pass

class TodoListError(Exception):
    """Исключение, связанное с ошибками в списке задач."""
    pass
